baseurl = "https://chazhyseni.github.io/NALgen"
languageCode = "en-us"
title = "NALgen: Neutral and Adaptive Landscape Genetics"
paginate = "10" # Number of posts per page
theme = "Mainroad"
googleAnalytics = "UA-139514839-1"
disqusShortname = ""

[Params]
  subtitle = "NALgen: Neutral and Adaptive Landscape Genetics" # Subtitle of your site
  description = "NALgen (Neutral and Adaptive Landscape Genetics) is a method for modeling the process of gene flow and predicting the resulting pattern of (neutral and adaptive) genetic variation across (continuous) landscapes." # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.logo]
   url = "SpEcEvGen.png"
    width = 100
    height = 100
    alt = "SpEcEvGen"

[Author]
  name = "Chaz Hyseni"
  bio = "Chaz has been doing research in the field of Population Genetics since 2006. He is interested in the distribution of genetic variation (both neutral and adaptive) in natural environments, at different spatial and temporal scales (from Landscape Genetics to Phylogeography). To understand pattern and process, Chaz uses empirical data as well as spatial eco-evolutionary modeling."
  avatar = "img/SpEcEvGen.png"


[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Vignettes"
    url = "/vignettes/"
    weight = 2

[[menu.main]]
    name = "Tutorials"
    url = "/tutorials/"
    weight = 3
